### ISSUE TITLE
Error while parsing the response of resource /3/0/11 (Object/Instance/ErrorCode)

### ISSUE THREAD

**Issue by davidfdezros** [jvermillard/leshan#57]
Hi guys,

I'm not sure if I'm doing something wrong, but when I read the Error Code resource  value (/3/0/11) on a device object, while parsing the response, the interface shows a message with something like "can't decode the tlv" and the console outputs the following stack trace:

![console-error](https://cloud.githubusercontent.com/assets/8007584/5682858/85d85c1c-9823-11e4-966f-2f7c183c12fd.png)

The received response packet is equals to, for example, read the resource 3/0/10.

![wireshark-3-0-10](https://cloud.githubusercontent.com/assets/8007584/5682659/e3e6f57c-9821-11e4-8a6a-3af1ee06c1e9.png)

![wireshark-3-0-11](https://cloud.githubusercontent.com/assets/8007584/5682664/ea6268b4-9821-11e4-8948-fc79e3ee6e40.png)

However if I read the entire object resources (/3/0), the value is successfully parsed (no error message) and printed in leshan.

What I'm missing or doing wrong?

Extra Info: I'm using a client based on wakaama implementations but using CoAP RFC.

**Comment by msangoi** [comment]
Hello,

I think your issue is related to the resource value format.
The /3/0/10 resource is a "single" resource, and when you try to read this resource, the value is expected to be in the "Plain text" format.
The /3/0/11 resource is a "multiple instance" resource, so the value is expected to be in "TLV" format (even if you have only one instance).

Your TLV parsing error probably occurs because the /3/0/11 value is returned in "Plain text" format.

No problem when reading the whole /3/0 instance because the content is encoded in TLV.

HTH
Manu

**Comment by davidfdezros** [comment]
Hi Manuel,

Thanks your for the fast answer, it's true, the problem is the value format. 

Thank you so much and sorry about the inconvenient, best regards,
David
